package:
  name: notebook_shortcut_anacondapro
  version: 0.1.3

build:
  number: 0
  skip: True # [not win]

requirements:
  run:
    - notebook

about:
  license: BSD
  summary: Console shortcut creator for Windows (using menuinst)

extra:
  recipe-maintainers:
    - bkreider
